plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton
#theme: jekyll-theme-dinky
title: Srijata Chakravorti, PhD
description: Data Scientist | Machine Learning

social_media:
  linkedin: srijatachakravorti
